name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu GCC
            os: ubuntu-latest
            cc: gcc-13
            cxx: g++-13
            build_type: Debug
            generator: "Unix Makefiles"

          - name: Windows MSVC
            os: windows-latest
            build_type: Release
            generator: "Visual Studio 17 2022"

          - name: macOS Clang
            os: macos-latest
            cc: clang
            cxx: clang++
            build_type: Debug
            generator: "Unix Makefiles"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Linux compilers
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y gcc-13 g++-13

    - name: Set up compilers
      if: runner.os != 'Windows'
      run: |
        echo "CC=${{ matrix.cc }}"  >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Configure CMake
      run: >
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DHART_BUILD_TESTS=ON -G "${{ matrix.config.generator }}"

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Test
      shell: bash
      working-directory: build
      run: ctest --output-on-failure --config ${{ matrix.build_type }}
