name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu AMD64 GCC
            os: ubuntu-latest
            cxx: g++-13
            build_type: Debug
            generator: "Unix Makefiles"
            cpp_compatibility_test: ON

          - name: Ubuntu ARM64 GCC
            os: ubuntu-24.04-arm
            cxx: g++-13
            build_type: Debug
            generator: "Unix Makefiles"
            cpp_compatibility_test: OFF

          - name: Ubuntu AMD64 Clang
            os: ubuntu-latest
            cxx: clang++-18
            build_type: Debug
            generator: "Unix Makefiles"
            cpp_compatibility_test: ON

          - name: Windows AMD64 MSVC
            os: windows-latest
            build_type: Release
            generator: "Visual Studio 17 2022"
            cpp_compatibility_test: ON

          - name: macOS ARM64 Apple-Clang
            os: macos-latest
            build_type: Debug
            generator: "Unix Makefiles"
            cpp_compatibility_test: OFF

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and set up Linux compilers
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cxx }}
        echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DHART_BUILD_TESTS=ON
        -DHART_CHECK_CPP_STANDARDS_COMPATIBILITY=${{ matrix.cpp_compatibility_test }}
        -G "${{ matrix.generator }}"

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure -V
